// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH_XFBrIhP6G7gdrtgauaT6ZKSi66QatQ',
    appId: '1:264827045295:web:e2f6ce6bccb6ca95a11b5a',
    messagingSenderId: '264827045295',
    projectId: 'travellerapp2025',
    authDomain: 'travellerapp2025.firebaseapp.com',
    storageBucket: 'travellerapp2025.firebasestorage.app',
    measurementId: 'G-HDLKH78F45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBks_G2Gj5Wz_eLnKk2O0K-_6KJgIMdIUg',
    appId: '1:264827045295:android:716abcb0d2fe6217a11b5a',
    messagingSenderId: '264827045295',
    projectId: 'travellerapp2025',
    storageBucket: 'travellerapp2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlx1An8zDLGtteACM3xToMHcRV1pWO5YI',
    appId: '1:264827045295:ios:517f4438ecaccc01a11b5a',
    messagingSenderId: '264827045295',
    projectId: 'travellerapp2025',
    storageBucket: 'travellerapp2025.firebasestorage.app',
    iosBundleId: 'com.example.traveller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlx1An8zDLGtteACM3xToMHcRV1pWO5YI',
    appId: '1:264827045295:ios:517f4438ecaccc01a11b5a',
    messagingSenderId: '264827045295',
    projectId: 'travellerapp2025',
    storageBucket: 'travellerapp2025.firebasestorage.app',
    iosBundleId: 'com.example.traveller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH_XFBrIhP6G7gdrtgauaT6ZKSi66QatQ',
    appId: '1:264827045295:web:a1fed636a121c25ea11b5a',
    messagingSenderId: '264827045295',
    projectId: 'travellerapp2025',
    authDomain: 'travellerapp2025.firebaseapp.com',
    storageBucket: 'travellerapp2025.firebasestorage.app',
    measurementId: 'G-00FPSPVWML',
  );

}